# Generated by Django 5.1 on 2024-08-20 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=20)),
                ('estado', models.CharField(choices=[('adoptado', 'Adoptado'), ('en_adopcion', 'En Adopción'), ('espera_de_adopcion', 'En Espera de Adopción')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('voluntario', 'Voluntario'), ('adoptante', 'Adoptante'), ('secreto_admin', 'Administrador')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('administrador', 'Administrador')], max_length=20)),
                ('contra', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('finalizado', 'Finalizado'), ('en_proceso', 'En Proceso')], max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animal')),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones_como_adoptante', to='api.usuario')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones_como_voluntario', to='api.usuario')),
            ],
        ),
    ]
