# Generated by Django 5.1 on 2024-08-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='adoptante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopciones_como_adoptante', to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.animal'),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='voluntario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopciones_como_voluntario', to='api.usuario'),
        ),
    ]
