# Generated by Django 5.1 on 2024-08-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_adopcion_fecha'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adopcion',
            constraint=models.UniqueConstraint(fields=('animal', 'adoptante'), name='unique_adopcion'),
        ),
    ]
