# Generated by Django 5.1 on 2024-08-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adopcion_unique_adopcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('voluntario', 'Voluntario'), ('adoptante', 'Adoptante'), ('administrador', 'Administrador')], max_length=20),
        ),
    ]
